Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ety"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ety"
    vb.memory = "2048"
    vb.cpus = "1"
  end
end
