Vagrant.configure("2") do |config|
  config.vm.define "rtyuio" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "rtyuio"
    machine.vm.network "private_network", ip: "192.168.56.4"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "rtyuio"
      vb.memory = "4096"
      vb.cpus = 2
    end

    # Provisioning : configuration du DNS sur la VM
    machine.vm.provision "shell", inline: <<-SHELL
      echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
    SHELL
  end
end
