Vagrant.configure("2") do |config|
  config.vm.define "gg" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "gg"
    machine.vm.network "private_network", ip: "192.168.56.4"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "gg"
      vb.memory = "4096"
      vb.cpus = 2
    end
    machine.vm.provision "shell", inline: <<-SHELL
      sudo rm -f /etc/resolv.conf
      echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
      sudo chattr +i /etc/resolv.conf  # Empêche la modification ultérieure
    SHELL
  end
  config.vm.define "hj" do |machine|
    machine.vm.box = "ubuntu/bionic64"
    machine.vm.hostname = "hj"
    machine.vm.network "private_network", ip: "192.168.56.2"
    machine.vm.provider "virtualbox" do |vb|
      vb.name = "hj"
      vb.memory = "4096"
      vb.cpus = 2
    end
    machine.vm.provision "shell", inline: <<-SHELL
      sudo rm -f /etc/resolv.conf
      echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
      sudo chattr +i /etc/resolv.conf  # Empêche la modification ultérieure
    SHELL
  end
end
